name: dailylotto
description: "lucky numbers recommended every day through AI"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  #firebase
  firebase_core: ^3.11.0
  cloud_firestore: ^5.6.3

  #ui
  unicons: ^3.0.0

  #ai
  flutter_gemini: ^3.0.0

  #bloc
  flutter_bloc: ^9.0.0

  #env
  flutter_dotenv: ^5.2.1

  #db
  shared_preferences: ^2.5.2

  #etc
  flutter_inappwebview: ^6.1.5
  equatable: ^2.0.7
  flutter_local_notifications: ^18.0.1
  flutter_native_timezone: ^2.0.0
  intl: ^0.20.2
  timezone: ^0.10.0
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
     - .env
