name: dailylotto
description: "lucky numbers recommended every day through AI"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.4+5

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  #firebase
  firebase_core: ^3.12.1
  cloud_firestore: ^5.6.5

  #ui
  unicons: ^3.0.0
  lottie: ^3.2.0
  smooth_page_indicator: ^1.2.0+3

  #bloc
  flutter_bloc: ^9.0.0

  #env
  flutter_dotenv: ^5.2.1
  package_info_plus: ^8.3.0

  #db
  shared_preferences: ^2.5.2
  hive_flutter: ^1.1.0
  hive: ^2.2.3

  #etc
  flutter_inappwebview: ^6.1.5
  equatable: ^2.0.7
  intl: ^0.20.2
  timezone: ^0.10.0
  permission_handler: ^11.3.1
  flutter_local_notifications: ^18.0.1
  firebase_messaging: ^15.2.2
  http: ^1.3.0
  get_it: ^8.0.3
  flutter_animate: ^4.5.2
  hugeicons: ^0.0.7
  url_launcher: ^6.3.1
  share_plus: ^10.1.4
  flutter_native_splash: ^2.4.5
  firebase_analytics: ^11.4.4
  fl_chart: ^0.70.2

flutter_native_splash:
  android: true
  ios: true
  web: true
  image: "assets/splash/splash_image_light.png"
  image_dark: "assets/splash/splash_image_dark.png"
  background_image: "assets/splash/splash_bg_light.png"
  background_image_dark: "assets/splash/splash_bg_dark.png"
  android_12:
    color: "#D9534F"
    color_dark: "#1E1E1E"
    image: "assets/splash/splash_image_android_light.png"
    image_dark: "assets/splash/splash_image_android_dark.png"

dev_dependencies:
  flutter_lints: ^4.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.13
  flutter_oss_licenses: ^3.0.4
  flutter_launcher_icons: ^0.14.3

  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
     - .env
     - assets/
     - assets/images/
     - assets/data/
     - assets/animations/
     - assets/icons/
     - assets/splash/

  fonts:
    - family: HakgyoansimGeurimilgi
      fonts:
        - asset: assets/fonts/Hakgyoansim_Geurimilgi_TTF_R.ttf

    - family: HakgyoansimWooju
      fonts:
        - asset: assets/fonts/HakgyoansimWoojuR.ttf